\c data_wharehouse_dev;

INSERT INTO jobs_users (fname, lname, email, phone, street,
city, state, zip, jobs_role, pwd,create_dt, last_updated) VALUES 
('Kenti','Johnson','kjohnson@gmail.com','6461234567','100 Main Street','New York','NY','10001','1','passSword',NOW(),NOW()),
('Clark','Kent','ckent@red_s.com','1234567890','100 Main Street','Smallsville','NY','10553','1','passSword',NOW(),NOW()),
('Peter','Parker','peter@webslinger.com','1234567890','25 Elm Street','Manhattan','NY','10121','true','passSword',NOW(), NOW()),
('Matt','Murdock','matt@daredevil.com','1234567890','29 Maple Drive','Central City','NY','10553','true','passSword',NOW(), NOW());

INSERT INTO jobs_user_profile (users_id,
profile_img, jobs_favorites, resume_doc, preferred_phone, preferred_email, create_dt, last_updated) VALUES 
(1,'default.jpg',ARRAY[1],'kjresume1.jpg','6461234567','kjohnson@gmail.com',NOW(),NOW()),
(2,'default.jpg',ARRAY[1],'ckresume1.jpg','6461234567','ckent@red_s.com',NOW(),NOW());

INSERT INTO jobs_listings (
  users_id, company, city, state, zip, work_remote, work_in_person, work_hybrid, about_the_company, main_industry, secondary_industry, tertiary_industry, headline, job_description, required_skills, Qualifications, we_look_for, compensation_range, job_status, create_dt, post_until_dt
) VALUES 
(1,'New York & Co','New York','NY','10010',false,true, false,'ABOUT THE COMPANY: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','Insurance','IT - Information Technology','Software Engineering','Javascript Developer','JOB DESCRIPTION: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', ARRAY['JavaScript','Python', 'HTML','CSS', 'React', 'Angular', 'PostgreSql'], ARRAY['Bachelor''s degree', 'Excellent knowledge UI/UX design including experience with shaders, textures, animation, GUI styles, and user session management','Strong understanding of object-oriented programming','Experience with 3D math is a plus','Prior experience with a well-known mobile or AAA title is a significant asset','Ability to constantly learn and stay in touch with evolving game standards and development technologies','Familiarity with current design and architectural patterns','Proficient knowledge of code versioning tools such as Perforce, Git, SVN, and Mercurial','Experience implementing automated testing platforms and unit tests','Experience with Game Network programming is a plus','Familiarity with baseball, baseball simulations/games, and gaming is a big plus'], ARRAY['Bachelors Degree','Three years experience with above skills','U.S. Citizenship or legal permanent residency','Able to work onsite','You have at least 2+ years of experience in developing web apps and shipping user-facing features with JavaScript and modern, component-based JS frameworks like React.', 
'You''ve developed and shipped user-facing features using component-based UI frameworks.',
'You''re familiar with current trends and best practices in front-end architecture, including performance, security and usability.',
'You''re familiar with product and design lifecycles, and collaborating closely with designers, engineers, and product managers.',
'You write high quality, well tested code to meet the needs of your customers.'], '$85K to $120K','open',NOW(), NOW()),
(1,'New York & Co','New York','NY','10010', true, false, false, 'ABOUT THE COMPANY: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','Insurance','IT - Information Technology','Software Engineering','Javascript Developer','JOB DESCRIPTION: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', ARRAY['JavaScript','Python', 'HTML','CSS', 'React', 'Angular', 'PostgreSql'], ARRAY['Bachelor''s degree', 'Excellent knowledge UI/UX design including experience with shaders, textures, animation, GUI styles, and user session management','Strong understanding of object-oriented programming','Experience with 3D math is a plus','Prior experience with a well-known mobile or AAA title is a significant asset','Ability to constantly learn and stay in touch with evolving game standards and development technologies','Familiarity with current design and architectural patterns','Proficient knowledge of code versioning tools such as Perforce, Git, SVN, and Mercurial','Experience implementing automated testing platforms and unit tests','Experience with Game Network programming is a plus','Familiarity with baseball, baseball simulations/games, and gaming is a big plus'], ARRAY['Bachelors Degree','Three years experience with above skills','U.S. Citizenship or legal permanent residency','Able to work onsite','You have at least 2+ years of experience in developing web apps and shipping user-facing features with JavaScript and modern, component-based JS frameworks like React.', 
'You''ve developed and shipped user-facing features using component-based UI frameworks.',
'You''re familiar with current trends and best practices in front-end architecture, including performance, security and usability.',
'You''re familiar with product and design lifecycles, and collaborating closely with designers, engineers, and product managers.',
'You write high quality, well tested code to meet the needs of your customers.'], '$85K to $120K','open',NOW(), NOW()),
(1,'New York & Co','New York','NY','10010', true, false, false, 'ABOUT THE COMPANY: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','Insurance','IT - Information Technology','Software Engineering','Javascript Developer','JOB DESCRIPTION: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', ARRAY['JavaScript','Python', 'HTML','CSS', 'React', 'Angular', 'PostgreSql'], ARRAY['Bachelor''s degree', 'Excellent knowledge UI/UX design including experience with shaders, textures, animation, GUI styles, and user session management','Strong understanding of object-oriented programming','Experience with 3D math is a plus','Prior experience with a well-known mobile or AAA title is a significant asset','Ability to constantly learn and stay in touch with evolving game standards and development technologies','Familiarity with current design and architectural patterns','Proficient knowledge of code versioning tools such as Perforce, Git, SVN, and Mercurial','Experience implementing automated testing platforms and unit tests','Experience with Game Network programming is a plus','Familiarity with baseball, baseball simulations/games, and gaming is a big plus'], ARRAY['Bachelors Degree','Three years experience with above skills','U.S. Citizenship or legal permanent residency','Able to work onsite','You have at least 2+ years of experience in developing web apps and shipping user-facing features with JavaScript and modern, component-based JS frameworks like React.', 
'You''ve developed and shipped user-facing features using component-based UI frameworks.',
'You''re familiar with current trends and best practices in front-end architecture, including performance, security and usability.',
'You''re familiar with product and design lifecycles, and collaborating closely with designers, engineers, and product managers.',
'You write high quality, well tested code to meet the needs of your customers.'], '$85K to $120K','open',NOW(), NOW()),
(1,'New York & Co','New York','NY','10010', true, false, false, 'ABOUT THE COMPANY: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','Insurance','IT - Information Technology','Software Engineering','Javascript Developer','JOB DESCRIPTION: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', ARRAY['JavaScript','Python', 'HTML','CSS', 'React', 'Angular', 'PostgreSql'], ARRAY['Bachelor''s degree', 'Excellent knowledge UI/UX design including experience with shaders, textures, animation, GUI styles, and user session management','Strong understanding of object-oriented programming','Experience with 3D math is a plus','Prior experience with a well-known mobile or AAA title is a significant asset','Ability to constantly learn and stay in touch with evolving game standards and development technologies','Familiarity with current design and architectural patterns','Proficient knowledge of code versioning tools such as Perforce, Git, SVN, and Mercurial','Experience implementing automated testing platforms and unit tests','Experience with Game Network programming is a plus','Familiarity with baseball, baseball simulations/games, and gaming is a big plus'], ARRAY['Bachelors Degree','Three years experience with above skills','U.S. Citizenship or legal permanent residency','Able to work onsite','You have at least 2+ years of experience in developing web apps and shipping user-facing features with JavaScript and modern, component-based JS frameworks like React.', 
'You''ve developed and shipped user-facing features using component-based UI frameworks.',
'You''re familiar with current trends and best practices in front-end architecture, including performance, security and usability.',
'You''re familiar with product and design lifecycles, and collaborating closely with designers, engineers, and product managers.',
'You write high quality, well tested code to meet the needs of your customers.'], '$85K to $120K','open',NOW(), NOW()),
(1,'New York & Co','New York','NY','10010', true, false, false, 'ABOUT THE COMPANY: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','Insurance','IT - Information Technology','Software Engineering','Javascript Developer','JOB DESCRIPTION: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', ARRAY['JavaScript','Python', 'HTML','CSS', 'React', 'Angular', 'PostgreSql'], ARRAY['Bachelor''s degree', 'Excellent knowledge UI/UX design including experience with shaders, textures, animation, GUI styles, and user session management','Strong understanding of object-oriented programming','Experience with 3D math is a plus','Prior experience with a well-known mobile or AAA title is a significant asset','Ability to constantly learn and stay in touch with evolving game standards and development technologies','Familiarity with current design and architectural patterns','Proficient knowledge of code versioning tools such as Perforce, Git, SVN, and Mercurial','Experience implementing automated testing platforms and unit tests','Experience with Game Network programming is a plus','Familiarity with baseball, baseball simulations/games, and gaming is a big plus'], ARRAY['Bachelors Degree','Three years experience with above skills','U.S. Citizenship or legal permanent residency','Able to work onsite','You have at least 2+ years of experience in developing web apps and shipping user-facing features with JavaScript and modern, component-based JS frameworks like React.', 
'You''ve developed and shipped user-facing features using component-based UI frameworks.',
'You''re familiar with current trends and best practices in front-end architecture, including performance, security and usability.',
'You''re familiar with product and design lifecycles, and collaborating closely with designers, engineers, and product managers.',
'You write high quality, well tested code to meet the needs of your customers.'], '$85K to $120K','open',NOW(), NOW()),
(1,'New York & Co','New York','NY','10010', false, true, false, 'ABOUT THE COMPANY: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','Insurance','IT - Information Technology','Software Engineering','Javascript Developer','JOB DESCRIPTION: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', ARRAY['JavaScript','Python', 'C#','HTML','CSS', 'React', 'Angular', 'PostgreSql'], ARRAY['Bachelor''s degree', 'Excellent knowledge UI/UX design including experience with shaders, textures, animation, GUI styles, and user session management','Strong understanding of object-oriented programming','Experience with 3D math is a plus','Prior experience with a well-known mobile or AAA title is a significant asset','Ability to constantly learn and stay in touch with evolving game standards and development technologies','Familiarity with current design and architectural patterns','Proficient knowledge of code versioning tools such as Perforce, Git, SVN, and Mercurial','Experience implementing automated testing platforms and unit tests','Experience with Game Network programming is a plus','Familiarity with baseball, baseball simulations/games, and gaming is a big plus'], ARRAY['Bachelors Degree','Three years experience with above skills','U.S. Citizenship or legal permanent residency','Able to work onsite','You have at least 2+ years of experience in developing web apps and shipping user-facing features with JavaScript and modern, component-based JS frameworks like React.', 
'You''ve developed and shipped user-facing features using component-based UI frameworks.',
'You''re familiar with current trends and best practices in front-end architecture, including performance, security and usability.',
'You''re familiar with product and design lifecycles, and collaborating closely with designers, engineers, and product managers.',
'You write high quality, well tested code to meet the needs of your customers.'], '$85K to $120K','open',NOW(), NOW()),
(1,'New York & Co','New York','NY','10010', false, true, false, 'ABOUT THE COMPANY: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','Insurance','IT - Information Technology','Software Engineering','Javascript Developer','JOB DESCRIPTION: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', ARRAY['JavaScript','Python', 'HTML','CSS', 'React', 'Angular', 'PostgreSql'], ARRAY['Bachelor''s degree', 'Excellent knowledge UI/UX design including experience with shaders, textures, animation, GUI styles, and user session management','Strong understanding of object-oriented programming','Experience with 3D math is a plus','Prior experience with a well-known mobile or AAA title is a significant asset','Ability to constantly learn and stay in touch with evolving game standards and development technologies','Familiarity with current design and architectural patterns','Proficient knowledge of code versioning tools such as Perforce, Git, SVN, and Mercurial','Experience implementing automated testing platforms and unit tests','Experience with Game Network programming is a plus','Familiarity with baseball, baseball simulations/games, and gaming is a big plus'], ARRAY['Bachelors Degree','Three years experience with above skills','U.S. Citizenship or legal permanent residency','Able to work onsite','You have at least 2+ years of experience in developing web apps and shipping user-facing features with JavaScript and modern, component-based JS frameworks like React.', 
'You''ve developed and shipped user-facing features using component-based UI frameworks.',
'You''re familiar with current trends and best practices in front-end architecture, including performance, security and usability.',
'You''re familiar with product and design lifecycles, and collaborating closely with designers, engineers, and product managers.',
'You write high quality, well tested code to meet the needs of your customers.'], '$85K to $120K','open',NOW(), NOW());

INSERT INTO jobs_likes (user_id,jobs_id,create_dt) 
VALUES 
(1,1,NOW()),
(2,1,NOW()),
(3,1,NOW()),
(1,2,NOW()),
(1,3,NOW()),
(1,3,NOW()),
(2,3,NOW());